name: Upload Release

on:
  push:
    tags:
      - v*

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    
    strategy:
      matrix:
        platform: [ "x86", "x64" ]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Set Up Python 3.7
      uses: actions/setup-python@main
      with:
        python-version: 3.7
        
    - name: Install pyinstaller
      run: | 
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        
    - name: Run pyinstaller
      run: pyinstaller -onefile audfill.py
      
    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: audfill-win-${{matrix.platform}}.exe
        path: dist/audfill.exe
        if-no-files-found: error

  upload:
    name: Upload Release
    needs: build-windows
    runs-on: ubuntu-latest

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
    
    - name: Upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          prerelease: false
          files: |
            *.exe
            *.zip
            LICENSE
